GateScorer/GateScorer/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('home/',include('home.urls')),
    path('quizz/', include('quiz.urls'))
]

GateScorer/home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns=[
    path('', views.index , name='index'),
    path( 'h_index/' , views.home_index, name='hindex'),
    path( 'about/',views.about,name='about'),
]

GateScorer/quiz/urls.py
from django.conf.urls import url
from .views import QuizListView, CategoriesListView,\
    ViewQuizListByCategory, QuizUserProgressView, QuizMarkingList,\
    QuizMarkingDetail, QuizDetailView, QuizTake
from django.urls import path

app_name="quizz"
urlpatterns = [       
                       url(regex=r'^quizzes/$',
                           view=QuizListView.as_view(),
                           name='quiz_index'),

                       url(regex=r'^category/$',
                           view=CategoriesListView.as_view(),
                           name='quiz_category_list_all'),

                       url(regex=r'^category/(?P<category_name>[\w|\W-]+)/$',
                           view=ViewQuizListByCategory.as_view(),
                           name='quiz_category_list_matching'),

                       url(regex=r'^progress/$',
                           view=QuizUserProgressView.as_view(),
                           name='quiz_progress'),

                       url(regex=r'^marking/$',
                           view=QuizMarkingList.as_view(),
                           name='quiz_marking'),

                       url(regex=r'^marking/(?P<pk>[\d.]+)/$',
                           view=QuizMarkingDetail.as_view(),
                           name='quiz_marking_detail'),

                       #  passes variable 'quiz_name' to quiz_take view
                       url(regex=r'^(?P<slug>[\w-]+)/$',
                           view=QuizDetailView.as_view(),
                           name='quiz_start_page'),

                       url(regex=r'^(?P<quiz_name>[\w-]+)/take/$',
                           view=QuizTake.as_view(),
                           name='quiz_question'),
]

GateScorer/home/models.py
from django.db import models
from django.contrib.auth.models import User


class CPerson(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    def __str__(self):
      return self.user.first_name+" "+self.user.last_name
    

GateScorer/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'home/homepage.html')

def home_index(request):
    return render(request,'home/homepage.html')

def quizz_index(request):
    return render(request,'quiz/base.html')

def about(request):
    return render(request,'home/about.html')

GateScorer/home/templates/home/about.html
{% load widget_tweaks %}
{% load static %}
 <!DOCTYPE html>
 <html>
 
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
        <meta name="author" content="Creative Tim">
        <title>Gate score Predictor</title>
        <!-- Favicon -->
        <link rel="icon" href="{% static 'home/assets/img/brand/favicon.png' %}" type="image/png">
        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
        <!-- Icons -->
        <link rel="stylesheet" href="{% static 'home/assets/vendor/nucleo/css/nucleo.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'home/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" type="text/css">
        <!-- Page plugins -->
        <!-- Argon CSS -->
        <link rel="stylesheet" href="{% static 'home/assets/css/argon.css' %}" type="text/css">
      
      
      
      </head>
 
 <body>
   <!-- Sidenav -->
 
   <nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">       
       <div class="sidenav-header d-flex align-items-center">         
         <a class="navbar-brand" href="#">
           <img src="{% static 'home/assets/img/brand/blue.png' %}" class="navbar-brand-img" alt="...">         
         </a>
         <div class="ml-auto">
           <!-- Sidenav toggler -->
           <div class="sidenav-toggler d-none d-xl-block" data-action="sidenav-unpin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
               <i class="sidenav-toggler-line"></i>
               <i class="sidenav-toggler-line"></i>
               <i class="sidenav-toggler-line"></i>
             </div>
          </div>
      </div>
      </div>
       <div class="navbar-inner">
         <!-- Collapse -->
         <div class="collapse navbar-collapse" id="sidenav-collapse-main">
           <!-- Nav items -->
           <ul class="navbar-nav">
             <li class="nav-item">
               <a class="nav-link" href="{% url 'quizz:quiz_index' %}">
                 <i class="ni ni-archive-2 text-green"></i>
                 <span class="nav-link-text">Score Predictor</span>
               </a>
             </li>
             <li class="nav-item">
               <a class="nav-link" href="#">
                 <i class="ni ni-single-copy-04 text-pink"></i>
                 <span class="nav-link-text">Previous Year Papers</span>
               </a>
             </li>
             <li class="nav-item">
               <a class="nav-link" href="{% url 'home:about' %}">
                 <i class="ni ni-single-copy-04 text-pink"></i>
                 <span class="nav-link-text">About</span>
               </a>
             </li>
           </ul>
        </div>
      </div>
      </div>
     </nav>
 
   <!-- Main content -->
   <div class="main-content" id="panel">
     <!-- Topnav -->
     <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
       <div class="container-fluid">
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <!-- Search form -->
           <!-- Navbar links -->
           <ul class="navbar-nav align-items-center ml-md-auto">
             <li class="nav-item d-xl-none">
               <!-- Sidenav toggler -->
               <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin"
                 data-target="#sidenav-main">
                 <div class="sidenav-toggler-inner">
                   <i class="sidenav-toggler-line"></i>
                   <i class="sidenav-toggler-line"></i>
                   <i class="sidenav-toggler-line"></i>
                 </div>
               </div>
             </li>
           </ul>
           <ul class="navbar-nav align-items-center ml-auto ml-md-0">
             <li class="nav-item dropdown">
               <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                 aria-expanded="false">
                 <div class="media align-items-center">
                   <span class="avatar avatar-sm rounded-circle">
                     <img alt="Image placeholder" src="assets/img/theme/team-4.jpg">
                   </span>
                   <div class="media-body ml-2 d-none d-lg-block">
                     <span class="mb-0 text-sm  font-weight-bold">Yagnik</span>
                   </div>
                 </div>
               </a>
               <div class="dropdown-menu dropdown-menu-right">
 
 
                 <a href="#!" class="dropdown-item">
                   <i class="ni ni-user-run"></i>
                   <span>Logout</span>
                 </a>
               </div>
             </li>
           </ul>
         </div>
       </div>
     </nav>
     <!-- Header -->
     <!-- Header -->
     <div class="header bg-primary pb-6">
       <div class="container-fluid">
         <div class="header-body">
           <div class="row p-1 ">
             <div class="col-lg-12 ">
               <div class="d-flex justify-content-center">
                 <h1 class="display-1" style="color:black;"> <strong>ABOUT</strong></h1>
               </div>
             </div>
           </div>
           <!-- Card stats -->
         </div>
       </div>
     </div>
     <!-- Page content -->
     <div class="d-flex justify-content-center">
     <div class="col-lg-8">
         <!-- Card body -->
         
         <div class="card-body">
             
           <p>This website is about predicting your Gate score. You can here give test and gain marks according to it
           and that marks will be stored in our database. Your marks and progreess will be accessed by us and we will apply our algorithm to predict your score</p>
           
     </div>
   </div>
   </div>
   <!-- Argon Scripts -->
   <!-- Core -->
   <script src="assets/vendor/jquery/dist/jquery.min.js"></script>
   <script src="assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
   <script src="assets/vendor/js-cookie/js.cookie.js"></script>
   <script src="assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
   <script src="assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>
   <!-- Optional JS -->
   <script src="assets/vendor/chart.js/dist/Chart.min.js"></script>
   <script src="assets/vendor/chart.js/dist/Chart.extension.js"></script>
   <!-- Argon JS -->
   <script src="assets/js/argon.js?v=1.1.0"></script>
   <!-- Demo JS - remove this in your project -->
   <script src="assets/js/demo.min.js"></script>
 </body>
 
 </html>