GateScorer/GateScorer/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('home/',include('home.urls')),
    path('quizz/', include('quiz.urls'))
]

GateScorer/home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns=[
    path('', views.index , name='index'),
    path( 'h_index/' , views.home_index, name='hindex'),
    path( 'about/',views.about,name='about'),
]

GateScorer/quiz/urls.py
from django.conf.urls import url
from .views import QuizListView, CategoriesListView,\
    ViewQuizListByCategory, QuizUserProgressView, QuizMarkingList,\
    QuizMarkingDetail, QuizDetailView, QuizTake
from django.urls import path

app_name="quizz"
urlpatterns = [       
                       url(regex=r'^quizzes/$',
                           view=QuizListView.as_view(),
                           name='quiz_index'),

                       url(regex=r'^category/$',
                           view=CategoriesListView.as_view(),
                           name='quiz_category_list_all'),

                       url(regex=r'^category/(?P<category_name>[\w|\W-]+)/$',
                           view=ViewQuizListByCategory.as_view(),
                           name='quiz_category_list_matching'),

                       url(regex=r'^progress/$',
                           view=QuizUserProgressView.as_view(),
                           name='quiz_progress'),

                       url(regex=r'^marking/$',
                           view=QuizMarkingList.as_view(),
                           name='quiz_marking'),

                       url(regex=r'^marking/(?P<pk>[\d.]+)/$',
                           view=QuizMarkingDetail.as_view(),
                           name='quiz_marking_detail'),

                       #  passes variable 'quiz_name' to quiz_take view
                       url(regex=r'^(?P<slug>[\w-]+)/$',
                           view=QuizDetailView.as_view(),
                           name='quiz_start_page'),

                       url(regex=r'^(?P<quiz_name>[\w-]+)/take/$',
                           view=QuizTake.as_view(),
                           name='quiz_question'),
]

GateScorer/quiz/forms.py
from django import forms
from django.forms.widgets import RadioSelect


class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [x for x in question.get_answers_list()]
        self.fields["answers"] = forms.ChoiceField(choices=choice_list, widget=RadioSelect)

GateScorer/quiz/views.py
import random

from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import FormView
from .forms import QuestionForm
from .models import Quiz, Category, Progress, Sitting, Question
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


class QuizMarkerMixin(object):
    @method_decorator(login_required)
    @method_decorator(permission_required('quiz.view_sittings'))
    def dispatch(self, *args, **kwargs):
        return super(QuizMarkerMixin, self).dispatch(*args, **kwargs)


class SittingFilterTitleMixin(object):
    def get_queryset(self):
        queryset = super(SittingFilterTitleMixin, self).get_queryset()
        quiz_filter = self.request.GET.get('quiz_filter')
        if quiz_filter:
            queryset = queryset.filter(quiz__title__icontains=quiz_filter)

        return queryset


class QuizListView(ListView):
    model = Quiz
    # @login_required
    def get_queryset(self):
        queryset = super(QuizListView, self).get_queryset()
        return queryset.filter(draft=False)


class QuizDetailView(DetailView):
    model = Quiz
    slug_field = 'url'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.draft and not request.user.has_perm('quiz.change_quiz'):
            raise PermissionDenied

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class CategoriesListView(ListView):
    model = Category


class ViewQuizListByCategory(ListView):
    model = Quiz
    template_name = 'view_quiz_category.html'

    def dispatch(self, request, *args, **kwargs):
        self.category = get_object_or_404(
            Category,
            category=self.kwargs['category_name']
        )

        return super(ViewQuizListByCategory, self).\
            dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ViewQuizListByCategory, self)\
            .get_context_data(**kwargs)

        context['category'] = self.category
        return context

    def get_queryset(self):
        queryset = super(ViewQuizListByCategory, self).get_queryset()
        return queryset.filter(category=self.category, draft=False)


class QuizUserProgressView(TemplateView):
    template_name = 'progress.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(QuizUserProgressView, self)\
            .dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(QuizUserProgressView, self).get_context_data(**kwargs)
        progress, c = Progress.objects.get_or_create(user=self.request.user)
        context['cat_scores'] = progress.list_all_cat_scores
        context['exams'] = progress.show_exams()
        return context


class QuizMarkingList(QuizMarkerMixin, SittingFilterTitleMixin, ListView):
    model = Sitting

    def get_queryset(self):
        queryset = super(QuizMarkingList, self).get_queryset()\
                                               .filter(complete=True)

        user_filter = self.request.GET.get('user_filter')
        if user_filter:
            queryset = queryset.filter(user__username__icontains=user_filter)

        return queryset
    
    class Meta:
        pass


class QuizMarkingDetail(QuizMarkerMixin, DetailView):
    model = Sitting

    def post(self, request, *args, **kwargs):
        sitting = self.get_object()

        q_to_toggle = request.POST.get('qid', None)
        if q_to_toggle:
            q = Question.objects.get_subclass(id=int(q_to_toggle))
            if int(q_to_toggle) in sitting.get_incorrect_questions:
                sitting.remove_incorrect_question(q)
            else:
                sitting.add_incorrect_question(q)

        return self.get(request)

    def get_context_data(self, **kwargs):
        context = super(QuizMarkingDetail, self).get_context_data(**kwargs)
        context['questions'] =\
            context['sitting'].get_questions(with_answers=True)
        return context


class QuizTake(FormView):
    form_class = QuestionForm
    template_name = 'question.html'

    def dispatch(self, request, *args, **kwargs):
        self.quiz = get_object_or_404(Quiz, url=self.kwargs['quiz_name'])
        if self.quiz.draft and not request.user.has_perm('quiz.change_quiz'):
            raise PermissionDenied

        self.logged_in_user = self.request.user.is_authenticated

        if self.logged_in_user:
            self.sitting = Sitting.objects.user_sitting(request.user,
                                                        self.quiz)
        if self.sitting is False:
            return render(request, 'single_complete.html')

        return super(QuizTake, self).dispatch(request, *args, **kwargs)

    def get_form(self, form_class=QuestionForm):
        if self.logged_in_user:
            self.question = self.sitting.get_first_question()
            self.progress = self.sitting.progress()
        return form_class(**self.get_form_kwargs())

    def get_form_kwargs(self):
        kwargs = super(QuizTake, self).get_form_kwargs()

        return dict(kwargs, question=self.question)

    def form_valid(self, form):
        if self.logged_in_user:
            self.form_valid_user(form)
            if self.sitting.get_first_question() is False:
                return self.final_result_user()
        self.request.POST = {}

        return super(QuizTake, self).get(self, self.request)

    def get_context_data(self, **kwargs):
        context = super(QuizTake, self).get_context_data(**kwargs)
        context['question'] = self.question
        context['quiz'] = self.quiz
        if hasattr(self, 'previous'):
            context['previous'] = self.previous
        if hasattr(self, 'progress'):
            context['progress'] = self.progress
        return context

    def form_valid_user(self, form):
        progress, c = Progress.objects.get_or_create(user=self.request.user)
        guess = form.cleaned_data['answers']
        is_correct = self.question.check_if_correct(guess)

        if is_correct is True:
            self.sitting.add_to_score(1)
            progress.update_score(self.question, 1, 1)
        else:
            self.sitting.add_incorrect_question(self.question)
            progress.update_score(self.question, 0, 1)

        if self.quiz.answers_at_end is not True:
            self.previous = {'previous_answer': guess,
                             'previous_outcome': is_correct,
                             'previous_question': self.question,
                             'answers': self.question.get_answers(),
                             'question_type': {self.question
                                               .__class__.__name__: True}}
        else:
            self.previous = {}

        self.sitting.add_user_answer(self.question, guess)
        self.sitting.remove_first_question()

    def final_result_user(self):
        results = {
            'quiz': self.quiz,
            'score': self.sitting.get_current_score,
            'max_score': self.sitting.get_max_score,
            'percent': self.sitting.get_percent_correct,
            'sitting': self.sitting,
            'previous': self.previous,
        }

        self.sitting.mark_quiz_complete()

        if self.quiz.answers_at_end:
            results['questions'] =\
                self.sitting.get_questions(with_answers=True)
            results['incorrect_questions'] =\
                self.sitting.get_incorrect_questions

        if self.quiz.exam_paper is False:
            self.sitting.delete()

        return render(self.request, 'result.html', results)

GateScorer/quiz/templates/quiz/category_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h2>{% trans "Category list" %}</h2>

<ul>
  {% for cat in category_list %}
  <li>
	<a href="{% url 'quizz:quiz_category_list_matching' category_name=cat.category %}">
	  {{ cat.category }}
	</a>
  </li>
  {% endfor %}
</ul>

{% endblock %}

GateScorer/quiz/templates/quiz/quiz_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
{{ quiz.title }}
{% endblock %}

{% block content %}
<h2>{{ quiz.title }}</h2>
<h3>{% trans "Category" %}: {{ quiz.category }}</h3>
{% if quiz.single_attempt %}
  <h4>{% trans "You will only get one attempt at this quiz" %}.</h4>
{% endif %}
<p>{{ quiz.description }}</p>
<p>
  <a href="{% url 'quizz:quiz_question' quiz_name=quiz.url %}">
	{% trans "Start quiz" %}
  </a>
</p>
{% endblock %}

GateScorer/quiz/templates/quiz/quiz_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load quiz_tags %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h2>{% trans "List of quizzes" %}</h2>
    {% if quiz_list %}
		<table class="table table-bordered table-striped">

		  <thead>
			<tr>
			  <th>{% trans "Title" %}</th>
			  <th>{% trans "Category" %}</th>
			  <th>{% trans "Exam" %}</th>
			  <th>{% trans "Single attempt" %}</th>
			  <th></th>
			</tr>
		  </thead>

		  <tbody>

        {% for quiz in quiz_list %}

  			<tr>
			  <td>{{ quiz.title }}</td>
			  <td>{{ quiz.category }}</td>
			  <td>{{ quiz.exam_paper }}</td>
			  <td>{{ quiz.single_attempt }}</td>
			  <td>
				<a href="{% url 'quizz:quiz_start_page' slug=quiz.url %}">
				  {% trans "View details" %}
				</a>
			</tr>

        {% endfor %}
		  </tbody>

		</table>

	{% else %}
        <p>{% trans "There are no available quizzes" %}.</p>
    {% endif %}
{% endblock %}

GateScorer/quiz/templates/quiz/sitting_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load quiz_tags %}
{% block title %}
{% trans "Result of" %} {{ sitting.quiz.title }} {% trans "for" %} {{ sitting.user }}
{% endblock %}

{% block content %}
<h2>{% trans "Quiz title" %}: {{ sitting.quiz.title }}</h2>
<h3>{% trans "Category" %}: {{ sitting.quiz.category }}</h3>
<p>{{ sitting.quiz.description }}</p>
<hr>
<p>{% trans "User" %}: {{ sitting.user }}</p>
<p>{% trans "Completed" %}: {{ sitting.end|date }}</p>
<p>{% trans "Score" %}: {{ sitting.get_percent_correct }}%</p>

<table class="table table-bordered table-striped">

  <thead>
	<tr>
	  <th>{% trans "Question" %}</th>
	  <th>{% trans "User answer" %}</th>
	  <th></th>
	  <th></th>
	</tr>
  </thead>

  <tbody>
{% for question in questions %}

	<tr>
      <td>
        {{ question.content }}
        {% if question.figure %}
        <div style="max-width: 100px;"><img src="{{ question.figure.url }}" alt="{{ question.figure }}"/></div>
        {% endif %}
      </td>
	  <td>{{ question|answer_choice_to_string:question.user_answer }}</td>
	  <td>
		{% if question.id in sitting.get_incorrect_questions %}
		  <p>{% trans "incorrect" %}</p>
		{% else %}
		  <p>{% trans "Correct" %}</p>
		{% endif %}
	  </td>
	  <td>
		<form action="" method="POST">{% csrf_token %}
		  <input type=hidden name="qid" value="{{ question.id }}">
		  <button type="submit" class="btn btn-warning">{% trans "Toggle whether correct" %}</button>
		</form>
	  </td>
	</tr>

{% endfor %}

  </tbody>

</table>
{% endblock %}

GateScorer/quiz/templates/quiz/sitting_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h2>{% trans "List of complete exams" %}</h2>
    {% if sitting_list %}

		<table class="table table-bordered table-striped">

		  <thead>
			<tr>
			  <th>{% trans "User" %}</th>
			  <th>{% trans "Quiz" %}</th>
			  <th>{% trans "Completed" %}</th>
			  <th>{% trans "Score" %}(%)</th>
			  <th></th>
			</tr>
		  </thead>

		  <tbody>
			<tr>
			  <form action="" method="GET">
				<td><input type="text" name="user_filter" /></td>
				<td><input type="text" name="quiz_filter" /></td>
				<td></td>
				<td></td>
				<td><button type="submit" class="btn btn-default">{% trans "Filter"%}</button></td>
			  </form>
			</tr>


        {% for sitting in sitting_list %}

			<tr>
			  <td>{{ sitting.user }}</td>
			  <td>{{ sitting.quiz }}</td>
			  <td>{{ sitting.end|date }}</td>
			  <td>{{ sitting.get_percent_correct }}</td>
			  <td>
				<a href="{% url 'quizz:quiz_marking_detail' pk=sitting.id %}">
				  {% trans "View details" %}
				</a>
			</tr>

        {% endfor %}

		  </tbody>

		</table>
    {% else %}
        <p>{% trans "There are no matching quizzes" %}.</p>
    {% endif %}
{% endblock %}